### PR TITLE
Allow symfony 7

### PR DESCRIPTION
**Pull request by thomasbeaujean**
Hi, this PR to allow SF7 in composer.json.

I also updated the tests, I had to remove the usage of AnnotationLoader that is not anymore in SF7

### CODE REVIEW

**Comment by epitre** [comment]
@Nyholm Is it still useful to support symfony 3.4, 4.4, etc... ?

**Comment by Nyholm** [comment]
No, I dont think so. Feel free to bump.

**Comment by epitre** [comment]
@thomasbeaujean good for you ?

**Comment by thomasbeaujean** [comment]
Done, I had to adapt the CI matrix to match the SF php compatibility.

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
